### ISSUE TITLE
"õ" =~ EXTRACT_FIELD_NAME_RE yields error

### ISSUE THREAD

**Issue by ZJvandeWeg** [terceiro/rmail#1]
For https://github.com/sup-heliotrope/sup/issues/205 the proposed fix was https://github.com/gauteh/rubymail/commit/2ee5086e942b15e46cc7c8265affee75f6b9d924. The equivalent is yet incorporated on this fork.

**Comment by terceiro** [comment]
Hi, can you provide a concrete test case containing the actual header that causes the issue?

**Comment by ZJvandeWeg** [comment]
I might have been to fast with this issue. 
Will look into it this weekend again. Sorry for wasting your time.

**Comment by gauteh** [comment]
Test message and tests for sup that currently fail are here: https://github.com/sup-heliotrope/sup/pull/214

**Comment by gauteh** [comment]
An incorrect fix is here: https://github.com/sup-heliotrope/rmail-sup/pull/3

**Comment by terceiro** [comment]
I tried feeding those messages to rmail and they are handled without issue, because rmail will not try to parse them. Even properly quoted non-ascii header values are returned as is with no parsing.

However the unquoted utf-8/latin1 data in header values will come back encoded as `ASCII-8BIT`, and that needs to be handled properly by whoever is using rmail.

In short, this does not look like something that can be fixed in rmail without breaking its API.

**Comment by maxmeyer** [comment]
What about using the constants from here? https://github.com/mikel/mail/blob/dc0f89bb33722ec1e6fa404a34055fe6e0189651/lib/mail/constants.rb

**Comment by maxmeyer** [comment]
This is quite an annoying bug. :-(
